### ISSUE TITLE
View All Tags

### ISSUE THREAD

**Issue by stevebrownlee** [day-cohort-70/rare-api-rare-bear-team-4#35]
As an admin I would like to see all the available Tags so that I can choose to edit or delete one, or see that I should add a new one.

**Given** an admin is in the app  
**When** they select the `Tag Management` link in the menu  
**Then** they should be directed to a page that lists all the Tag names ordered alphabetically  

> **NOTE:** For the time being it is acceptable to treat all users as `admin` users. There is a future story about enforcing user permissions.

**Comment by Sydney-M-Sharp** [comment]
I will be working on this ticket for all users not just admins.

**Comment by Sydney-M-Sharp** [comment]
created pull request here https://github.com/day-cohort-70/rare-client-rare-bear-team-4/pull/1

**Comment by Sydney-M-Sharp** [comment]
pull request reviewed. 
Basic view of all tags with no css now pushed to develop
