### ISSUE TITLE
Dev: Comment  CRUD Back End Work

### ISSUE THREAD

**Issue by Sydney-M-Sharp** [day-cohort-70/rare-api-rare-bear-team-4#80]
![Image](https://github.com/day-cohort-70/rare-api-rare-bear-team-4/assets/159806068/25e70eaf-96fd-4e91-882c-389cb075a047)

CRUD needed for the comment back end before moving forward with front

**Comment by Sydney-M-Sharp** [comment]
Working on this as a team but then Sydney does one on her own.

**Comment by Marceline-G** [comment]
Finished with 
https://github.com/day-cohort-70/rare-api-rare-bear-team-4/pull/94
